services:
  # ==========================================
  # 1. DATABASE & BI TOOL (Data Mart Layer)
  # ==========================================
  postgres:
    image: postgres:15-alpine
    container_name: stream_postgres
    hostname: postgres
    networks:
      - streaming-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: glamira_db
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d 
    deploy:
      resources:
        limits:
          memory: 256M

  metabase:
    image: metabase/metabase:latest
    container_name: stream_metabase
    networks:
      - streaming-network
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db 
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: password123
      MB_DB_HOST: postgres
      JAVA_TOOL_OPTIONS: "-Xmx512m"
    depends_on:
      - postgres
    volumes:
      - ../metabase_data:/metabase-data
    deploy:
      resources:
        limits:
          memory: 1G

  # ==========================================
  # 2. HADOOP CLUSTER (Storage & Resource Layer)
  # ==========================================
  namenode:
    build: . 
    image: my-hadoop-cluster:3.3.6 
    networks:
      - streaming-network
    hostname: namenode
    container_name: namenode
    command: /usr/local/bin/start-namenode.sh
    ports:
      - '9870:9870' 
    volumes:
      - namenode_data:/data
      - ./conf:/usr/local/hadoop/etc/hadoop 
    deploy:
      resources:
        limits:
          memory: 512M

  datanode1:
    image: my-hadoop-cluster:3.3.6
    networks:
      - streaming-network
    hostname: datanode1
    container_name: datanode1
    command: [ "hdfs", "datanode" ]
    volumes:
      - datanode1_data:/data
      - ./conf:/usr/local/hadoop/etc/hadoop
    deploy:
      resources:
        limits:
          memory: 512M

  resourcemanager:
    image: my-hadoop-cluster:3.3.6
    networks:
      - streaming-network
    hostname: resourcemanager
    container_name: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - '8088:8088' 
    volumes:
      - resourcemanager_data:/data
      - ./conf:/usr/local/hadoop/etc/hadoop
    deploy:
      resources:
        limits:
          memory: 512M

  nodemanager1:
    image: my-hadoop-cluster:3.3.6
    networks:
      - streaming-network
    hostname: nodemanager1
    container_name: nodemanager1
    command: [ "yarn", "nodemanager" ]
    volumes:
      - nodemanager1_data:/data
      - ./conf:/usr/local/hadoop/etc/hadoop
    deploy:
      resources:
        limits:
          memory: 1G

  # ==========================================
  # 3. SPARK CLIENT (Processing Layer)
  # ==========================================
  spark-client:
    build: 
      context: ./spark-client
      dockerfile: Dockerfile
    container_name: spark-client
    hostname: spark-client
    networks:
      - streaming-network
    command: tail -f /dev/null
    env_file:
      - ../.env
    environment:
      - HADOOP_CONF_DIR=/opt/spark/hadoop-conf
      - SPARK_HOME=/opt/spark
    ports:
      - "4040:4040" 
    volumes:
      - ../:/workspace
      - ./conf:/opt/spark/hadoop-conf
      - ivy2-cache:/home/spark/.ivy2
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  streaming-network:
    name: streaming-network
    driver: bridge

volumes:
  namenode_data:
  datanode1_data:
  resourcemanager_data:
  nodemanager1_data:
  pg_data:
  ivy2-cache: